version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"  
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  test:
    build:
      context: .
      dockerfile: test/Dockerfile
    container_name: test-container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5433;Database=testdb;Username=root;Password=password"  # Updated connection string to use Port=5433
    networks:
      - app-network
    restart: always

networks:
  app-network:

volumes:
  postgres-data:
